/**
 * Section assembly — turns one ranked pool into the page's rails.
 *
 * Sections are carved out of a single scored pool rather than generated by
 * separate ranking passes, so a title cannot appear in three rails at once and
 * every section inherits the same scoring semantics. Each section also owns a
 * `reason` string built from the signals that defined it, and any section that
 * cannot be filled honestly is omitted instead of padded.
 */

import type {
  Recommendation,
  RecommendationSection,
  ScoredCandidate,
  TasteProfile,
} from "@/types/recommendations";

import { DIVERSITY, SCORING, SECTIONS, TIER_THRESHOLD } from "./config";
import { describeDiversity, diversify } from "./diversify";
import { explain } from "./explain";
import { toTenPoint } from "./rating";

/* -------------------------------------------------------------------------- */
/* Helpers                                                                    */
/* -------------------------------------------------------------------------- */

function toRecommendation(
  scored: ScoredCandidate,
  profile: TasteProfile,
  sectionId: string,
  rank: number,
  includeFactors: boolean,
): Recommendation {
  return {
    key: scored.candidate.key,
    media: scored.candidate.media,
    score: scored.score,
    tier: scored.tier,
    confidence: scored.confidence,
    explanation: explain(scored, profile),
    sectionId,
    rank,
    ...(includeFactors ? { factors: scored.factors } : {}),
  };
}

interface SectionBuildContext {
  profile: TasteProfile;
  includeFactors: boolean;
  /** Keys already placed in an earlier section. */
  used: Set<string>;
}

function buildSection(
  context: SectionBuildContext,
  spec: {
    id: string;
    kind: RecommendationSection["kind"];
    title: string;
    reason: string;
    items: ScoredCandidate[];
  },
): RecommendationSection | null {
  if (spec.items.length === 0) return null;

  const items = spec.items.map((scored, index) =>
    toRecommendation(scored, context.profile, spec.id, index + 1, context.includeFactors),
  );

  for (const item of items) context.used.add(item.key);

  return { id: spec.id, kind: spec.kind, title: spec.title, reason: spec.reason, items };
}

function unused(pool: ScoredCandidate[], used: Set<string>): ScoredCandidate[] {
  return pool.filter((item) => !used.has(item.candidate.key));
}

function hasFactor(item: ScoredCandidate, key: string): boolean {
  return item.factors.some((f) => f.key === key && f.contribution > 0);
}

/* -------------------------------------------------------------------------- */
/* Reason copy                                                                */
/* -------------------------------------------------------------------------- */

function topGenreNames(profile: TasteProfile, count: number): string[] {
  return profile.genres
    .filter((g) => g.score > 0)
    .slice(0, count)
    .map((g) => g.key);
}

function joinList(values: string[]): string {
  if (values.length === 0) return "";
  if (values.length === 1) return values[0]!;
  return `${values.slice(0, -1).join(", ")} and ${values[values.length - 1]}`;
}

/**
 * Describes the evidence behind Top Picks in the user's own terms.
 * Only mentions inputs that exist: no ratings ⇒ ratings are not mentioned.
 */
function topPicksReason(profile: TasteProfile): string {
  const parts: string[] = [];
  const genres = topGenreNames(profile, 2);
  if (genres.length > 0) parts.push(`your ${joinList(genres).toLowerCase()} history`);
  if (profile.ratings.count > 0) parts.push(`${profile.ratings.count} ratings`);
  if (profile.anchors.length > 0) parts.push(`${profile.anchors.length} standout titles`);
  if (profile.completion.droppedCount > 0) {
    parts.push(`what you have dropped`);
  }
  if (parts.length === 0) return "Ranked from your library.";
  return `Ranked from ${joinList(parts)}.`;
}

/* -------------------------------------------------------------------------- */
/* Personalized feed                                                          */
/* -------------------------------------------------------------------------- */

export interface AssembleOptions {
  /** Include the full factor breakdown on every item (debug mode only). */
  includeFactors?: boolean;
}

export function assembleSections(
  pool: ScoredCandidate[],
  profile: TasteProfile,
  options: AssembleOptions = {},
): RecommendationSection[] {
  const context: SectionBuildContext = {
    profile,
    includeFactors: options.includeFactors ?? false,
    used: new Set<string>(),
  };

  const sections: RecommendationSection[] = [];

  /* Top picks — the strongest items, diversified. ------------------------- */
  const topPicks = buildSection(context, {
    id: "top-picks",
    kind: "top_picks",
    title: "Top picks for you",
    reason: topPicksReason(profile),
    items: diversify(pool, { limit: SECTIONS.topPicks }),
  });
  if (topPicks) sections.push(topPicks);

  /* Because you watched — one cluster per strongest anchor. --------------- */
  let clusters = 0;
  for (const anchor of profile.anchors) {
    if (clusters >= SECTIONS.maxAnchorClusters) break;

    const anchored = unused(pool, context.used).filter((item) =>
      item.candidate.provenance.some((p) => p.anchorExternalId === anchor.externalId),
    );
    if (anchored.length < SECTIONS.minAnchorCluster) continue;

    // Caps are ignored here: a cluster is one anchor's neighbourhood by
    // definition, and genre spread inside it is not a virtue.
    const items = diversify(anchored, {
      limit: SECTIONS.perAnchorCluster,
      relevanceWeight: 0.9,
      ignoreCaps: true,
    });
    if (items.length < SECTIONS.minAnchorCluster) continue;

    const verb =
      anchor.basis === "rated_high"
        ? "you rated"
        : anchor.basis === "rewatched"
          ? "you rewatched"
          : anchor.basis === "favorite"
            ? "you favourited"
            : "you watched";

    const section = buildSection(context, {
      id: `anchor-${anchor.mediaType}-${anchor.externalId}`,
      kind: "because_you_watched",
      title: `Because ${verb} ${anchor.title}`,
      reason:
        anchor.rating != null
          ? `You rated it ${toTenPoint(anchor.rating).toFixed(1)}/10.`
          : `Drawn from titles the catalog links to ${anchor.title}.`,
      items,
    });
    if (section) {
      sections.push(section);
      clusters += 1;
    }
  }

  /* Matches your taste — attribute-driven rather than title-driven. ------- */
  const tasteCandidates = unused(pool, context.used).filter(
    (item) =>
      hasFactor(item, "genre_affinity") ||
      hasFactor(item, "people_affinity") ||
      hasFactor(item, "era_fit") ||
      hasFactor(item, "theme_overlap"),
  );
  const tasteReasonParts: string[] = [];
  const tasteGenres = topGenreNames(profile, 3);
  if (tasteGenres.length > 0) tasteReasonParts.push(joinList(tasteGenres).toLowerCase());
  const topDecade = profile.decades.find((d) => d.score > 0)?.key;
  if (topDecade) tasteReasonParts.push(`the ${topDecade}`);
  const topCreator = profile.creators.find((c) => c.score > 0.2)?.key;
  if (topCreator) tasteReasonParts.push(topCreator);

  const matchesTaste = buildSection(context, {
    id: "matches-taste",
    kind: "matches_taste",
    title: "Matches your taste",
    reason:
      tasteReasonParts.length > 0
        ? `Built from your pull toward ${joinList(tasteReasonParts)}.`
        : "Built from the attributes your library leans on.",
    items: diversify(tasteCandidates, { limit: SECTIONS.matchesTaste }),
  });
  if (matchesTaste) sections.push(matchesTaste);

  /* Hidden gems — high affinity, low reach. Verifiable, not just obscure. - */
  const gems = unused(pool, context.used).filter((item) => {
    const popularity = item.candidate.media.popularity ?? 0;
    const votes = item.candidate.media.voteCount ?? 0;
    const vote = item.candidate.media.voteAverage ?? 0;
    return (
      popularity > 0 &&
      popularity < SCORING.mainstreamPopularity &&
      votes >= 100 &&
      vote >= 6.8 &&
      item.score >= TIER_THRESHOLD.discovery
    );
  });
  const hiddenGems = buildSection(context, {
    id: "hidden-gems",
    kind: "hidden_gems",
    title: "Hidden gems",
    reason:
      "Well-reviewed titles that fit your profile but get far less attention than your usual picks.",
    items: diversify(gems, { limit: SECTIONS.hiddenGems, relevanceWeight: 0.6 }),
  });
  if (hiddenGems) sections.push(hiddenGems);

  /* Discover something different — deliberate departure. ------------------ */
  const different = unused(pool, context.used).filter(
    (item) =>
      hasFactor(item, "discovery") ||
      item.tier === "wildcard" ||
      // Titles with no genre overlap at all still belong here when their own
      // quality carries them; that is the definition of adjacent discovery.
      (!hasFactor(item, "genre_affinity") && hasFactor(item, "quality")),
  );
  const discoverDifferent = buildSection(context, {
    id: "discover-different",
    kind: "discover_different",
    title: "Discover something different",
    reason:
      profile.avoidedGenres.length > 0
        ? `Steps outside your habits, while avoiding ${joinList(
            profile.avoidedGenres.slice(0, 2).map((g) => g.key.toLowerCase()),
          )}.`
        : "Deliberately outside your usual genres and eras.",
    items: diversify(different, {
      limit: SECTIONS.discoverDifferent,
      relevanceWeight: 0.45,
    }),
  });
  if (discoverDifferent) sections.push(discoverDifferent);

  /* Per-media-type rails — only when both are genuinely well stocked. ----- */
  const remaining = unused(pool, context.used);
  const movies = remaining.filter((i) => i.candidate.media.mediaType === "movie");
  const shows = remaining.filter((i) => i.candidate.media.mediaType === "tv");

  if (
    movies.length >= SECTIONS.minMediaTypeSection &&
    shows.length >= SECTIONS.minMediaTypeSection
  ) {
    const movieSection = buildSection(context, {
      id: "films",
      kind: "movies",
      title: "Films to line up",
      reason:
        profile.runtime.meanMinutes != null
          ? `You tend to watch around ${profile.runtime.meanMinutes} minutes at a time.`
          : "Ranked the same way, films only.",
      items: diversify(movies, { limit: SECTIONS.perMediaType }),
    });
    if (movieSection) sections.push(movieSection);

    const showSection = buildSection(context, {
      id: "series",
      kind: "shows",
      title: "Series to start",
      reason: profile.completion.avoidsLongSeries
        ? "Weighted toward shorter runs, since long series are the ones you drop."
        : "Ranked the same way, series only.",
      items: diversify(shows, { limit: SECTIONS.perMediaType }),
    });
    if (showSection) sections.push(showSection);
  }

  return sections.filter((section) => section.items.length > 0);
}

/* -------------------------------------------------------------------------- */
/* Cold start                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Feed for a user with no usable history.
 *
 * Kept structurally separate from the personalized path and labelled as generic
 * discovery. Claiming to know the taste of a user with an empty library is the
 * fastest way to lose their trust in every later recommendation.
 */
export function assembleColdStartSections(
  pool: ScoredCandidate[],
  profile: TasteProfile,
  options: AssembleOptions = {},
): RecommendationSection[] {
  const context: SectionBuildContext = {
    profile,
    includeFactors: options.includeFactors ?? false,
    used: new Set<string>(),
  };

  const sections: RecommendationSection[] = [];

  const byQuality = [...pool].sort((a, b) => {
    const delta =
      (b.candidate.media.voteAverage ?? 0) - (a.candidate.media.voteAverage ?? 0);
    if (Math.abs(delta) > 1e-9) return delta;
    return a.candidate.key.localeCompare(b.candidate.key);
  });

  const trending = pool.filter((i) =>
    i.candidate.provenance.some((p) => p.source === "trending"),
  );
  const acclaimed = byQuality.filter(
    (i) =>
      i.candidate.provenance.some((p) => p.source === "acclaimed") &&
      (i.candidate.media.voteCount ?? 0) >= 500,
  );
  const fresh = pool.filter((i) =>
    i.candidate.provenance.some((p) => p.source === "fresh_release"),
  );

  const trendingSection = buildSection(context, {
    id: "cold-trending",
    kind: "cold_start",
    title: "Trending now",
    reason: "Not personalized — Argus has nothing to learn from yet.",
    items: diversify(trending, {
      limit: SECTIONS.coldStart,
      relevanceWeight: DIVERSITY.relevanceWeight,
    }),
  });
  if (trendingSection) sections.push(trendingSection);

  const acclaimedSection = buildSection(context, {
    id: "cold-acclaimed",
    kind: "cold_start",
    title: "Widely acclaimed",
    reason: "Highest-rated titles in the catalog, as a starting point.",
    items: diversify(unused(acclaimed, context.used), { limit: SECTIONS.coldStart }),
  });
  if (acclaimedSection) sections.push(acclaimedSection);

  const freshSection = buildSection(context, {
    id: "cold-fresh",
    kind: "cold_start",
    title: "New releases",
    reason: "Recent arrivals across genres.",
    items: diversify(unused(fresh, context.used), {
      limit: SECTIONS.coldStart,
      relevanceWeight: 0.5,
    }),
  });
  if (freshSection) sections.push(freshSection);

  return sections.filter((section) => section.items.length > 0);
}

export { describeDiversity };
